version: "3.9"

services:
  nginx:
    build: nginx
    ports:
      - "8804:8804"
    depends_on:
      - ktor
    restart: always
    secrets:
      - ssl_public_key_site
      - ssl_private_key_site
      - ssl_private_key_jwk
  ktor:
    build: .
    volumes:
      - assets:/assets
    depends_on:
      - mariadb
      - gemini
    dns:
      - 8.8.8.8
    environment:
      SMTP_SERVER: "${SMTP_SERVER}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_LOGIN: "${SMTP_LOGIN}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      TASKS_AUTH_ISSUER: "${TASKS_AUTH_ISSUER}"
      TASKS_AUTH_PUBLIC_KEY_ID: "${TASKS_AUTH_PUBLIC_KEY_ID}"
      TASKS_AUTH_PRIVATE_KEY_PATH: "/run/secrets/ssl_private_key_jwk"
      TASKS_DATA_SOURCE_URL: "jdbc:mariadb://mariadb:3306/tasks"
      TASKS_BASE_URL: "https://tasks-api.chara.dev"
      TASKS_ASSETS_FOLDER: "/assets"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      GEMINI_HOST: "${GEMINI_HOST}"
      GEMINI_PORT: "${GEMINI_PORT}"
    secrets:
      - google_service_account
      - ssl_private_key_jwk
    restart: always
  mariadb:
    build: mariadb
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
  gemini:
    build: gemini
    volumes:
      - classifiers:/classifiers
    environment:
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
    devices:
      - /dev/kfd
    security_opt:
      - seccomp=unconfined
    restart: always

volumes:
  assets:
  db:
  classifiers:

secrets:
  google_service_account:
    file: /root/.tasks/service-account.json
  ssl_public_key_site:
    file: /etc/letsencrypt/live/dominaria.chara.dev/fullchain.pem
  ssl_private_key_site:
    file: /etc/letsencrypt/live/dominaria.chara.dev/privkey.pem
  ssl_private_key_jwk:
    file: /root/.tasks/certs/private/jwk_private.pkcs